### ISSUE TITLE
Docsify init error (SyntaxError: Unexpected token =)

### ISSUE THREAD

**Issue by etigui** [docsifyjs/docsify-cli#210]
### Version 
npm: 6.14.4

### Steps to reproduce

```
$ sudo npm install docsify-cli -g                                                                                                                                              
/usr/local/bin/docsify -> /usr/local/lib/node_modules/docsify-cli/bin/docsify
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/docsify-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ docsify-cli@4.4.4
updated 1 package in 18.77s

$ docsify init docs
/usr/local/lib/node_modules/docsify-cli/node_modules/enquirer/lib/queue.js:4
  _queue = [];
         ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/docsify-cli/node_modules/enquirer/lib/keypress.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by shine-fire** [comment]
I'm having the same issue

**Comment by diablov** [comment]
same, use nodejs16 solve.

**Comment by sy-records** [comment]
Please use a high version of nodejs.
