### ISSUE TITLE
升级cli后报错

### ISSUE THREAD

**Issue by prlei** [docsifyjs/docsify-cli#36]
升级了cli，新建一个doc，然后启动报错（旧版本的启动正常，我是建了个新的）：

⇒  docsify serve .
*** DEPRECATION WARNING *** The exts option will REPLACE extensions in 0.6.4. ***

Serving /Users/leic/hepbum/document/radarjavadoc now.
Listening at http://localhost:3000

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::35729
    at Server.setupListenHandle [as _listen2] (net.js:1327:14)
    at listenInCluster (net.js:1375:12)
    at Server.listen (net.js:1462:7)
    at Server.listen (/usr/local/lib/node_modules/docsify-cli/node_modules/livereload/lib/livereload.js:69:28)
    at Object.exports.createServer (/usr/local/lib/node_modules/docsify-cli/node_modules/livereload/lib/livereload.js:229:14)
    at Object.module.exports [as serve] (/usr/local/lib/node_modules/docsify-cli/lib/commands/serve.js:30:12)
    at Object.handler (/usr/local/lib/node_modules/docsify-cli/bin/docsify:77:28)
    at Object.self.runCommand (/usr/local/lib/node_modules/docsify-cli/node_modules/yargs/lib/command.js:231:22)
    at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/docsify-cli/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/docsify-cli/node_modules/yargs/yargs.js:930:19)
Emitted 'error' event at:
    at Server.WebSocketServer._onServerError (/usr/local/lib/node_modules/docsify-cli/node_modules/ws/lib/WebSocketServer.js:82:50)
    at Server.emit (events.js:182:13)
    at emitErrorNT (net.js:1354:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

**Comment by prlei** [comment]
发现了，是因为我启动多个的问题，不过我确实需要启动多个，并且我换端口了 一个3070  一个3071，反正启动一个 另一个就起不来？怎么破？

**Comment by juhuan** [comment]
我跟你同样的问题，而且本地可以搜索，但是服务器搜索不了

**Comment by anikethsaha** [comment]
please translate to english
