### ISSUE TITLE
如何修改livereload固定监听端口35729导致不可启动多个docsify实例？

### ISSUE THREAD

**Issue by fananzhi** [docsifyjs/docsify-cli#51]
我使用不同端口启用两个docsify serve，但报错端口重用：

=============
#docsify serve base --port 30001

Serving /data1/anlanfan/tgp/trunk/server/src/docs/docsify/base now.
Listening at http://localhost:30001

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::35729
    at Server.setupListenHandle [as _listen2] (net.js:1290:14)
    at listenInCluster (net.js:1338:12)
    at Server.listen (net.js:1425:7)
    at Server.listen (/data1/software/node-v10.14.2-linux-x64/lib/node_modules/docsify-cli/node_modules/livereload/lib/livereload.js:80:28)
    at Object.exports.createServer (/data1/software/node-v10.14.2-linux-x64/lib/node_modules/docsify-cli/node_modules/livereload/lib/livereload.js:246:14)
    at Object.module.exports [as serve] (/data1/software/node-v10.14.2-linux-x64/lib/node_modules/docsify-cli/lib/commands/serve.js:30:12)
    at Object.handler (/data1/software/node-v10.14.2-linux-x64/lib/node_modules/docsify-cli/bin/docsify:77:28)
    at Object.self.runCommand (/data1/software/node-v10.14.2-linux-x64/lib/node_modules/docsify-cli/node_modules/yargs/lib/command.js:231:22)
    at Object.Yargs.self._parseArgs (/data1/software/node-v10.14.2-linux-x64/lib/node_modules/docsify-cli/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/data1/software/node-v10.14.2-linux-x64/lib/node_modules/docsify-cli/node_modules/yargs/yargs.js:930:19)
Emitted 'error' event at:
    at Server.onError (/data1/software/node-v10.14.2-linux-x64/lib/node_modules/docsify-cli/node_modules/livereload/lib/livereload.js:99:19)
    at WebSocketServer.emit (events.js:182:13)
    at Server.WebSocketServer._onServerError (/data1/software/node-v10.14.2-linux-x64/lib/node_modules/docsify-cli/node_modules/ws/lib/WebSocketServer.js:82:50)
    at Server.emit (events.js:182:13)
    at emitErrorNT (net.js:1317:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by ls9527** [comment]
使用大写的-P 指定即可。

例如用以下方式开启多个服务器： 
1. docsify serve ./ -p 15000 --open -P 35800
2. docsify serve ./ -p 16000 --open -P 35900
3. docsify serve ./ -p 17000 --open -P 36000

通过文件docsify查看支持的命令： %AppData%\npm\node_modules\docsify-cli\bin\docsify

**Comment by ls9527** [comment]
如果你希望修改md文档之后，立马在界面看到效果 -p 指定的内容要在 3000-4999 之间。

**Comment by anikethsaha** [comment]
please translate to english
