### ISSUE TITLE
[bug] Recent version of master: Error: EMFILE: too many open files, watch

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify-cli#62]
First of all, great project!! Loving it!!

Version 4.3.0 works great. However, I just tried `master` branch, on 78761d60cec0dd1deeda909a07320780e5aabff5, and now `docsify serve` gives me an error:

<details><summary>see output:</summary>

```
❯ npm run docs

> infamous@21.0.6 docs /Users/trusktr/src/infamous+infamous
> docsify serve ./docs

Serving /Users/trusktr/src/infamous+infamous/docs now.
Listening at http://localhost:3000

2019-08-18 21:54 node[73865] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2019-08-18 21:54 node[73865] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2019-08-18 21:54 node[73865] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2019-08-18 21:54 node[73865] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
Emitted 'error' event at:
    at FSWatcher._handleError (/Users/trusktr/src/docsifyjs+docsify-cli/node_modules/chokidar/index.js:257:10)
    at /Users/trusktr/src/docsifyjs+docsify-cli/node_modules/chokidar/lib/nodefs-handler.js:54:5
    at Array.forEach (<anonymous>)
    at fsWatchBroadcast (/Users/trusktr/src/docsifyjs+docsify-cli/node_modules/chokidar/lib/nodefs-handler.js:53:36)
    at FSWatcher.<anonymous> (/Users/trusktr/src/docsifyjs+docsify-cli/node_modules/chokidar/lib/nodefs-handler.js:97:9)
    at FSWatcher.emit (events.js:203:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! infamous@21.0.6 docs: `docsify serve ./docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the infamous@21.0.6 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trusktr/.npm/_logs/2019-08-19T04_54_38_178Z-debug.log
```

</details>

Maybe this has something to do with removal of gulp?

https://github.com/facebook/create-react-app/issues/4540 may provide clues to a possible solution.

For now, I'll be forked from 4.3.0 so that I can add some `connect` handlers and move along with my project (after updating hacked event-stream 🙊).

**Comment by trusktr** [comment]
Hmmm, looks like I'm getting this error on 4.3.0 now. Seems something changed in my system, not in docsify-cli.

**Comment by trusktr** [comment]
Closing for now
