### ISSUE TITLE
Bug: docs init ./docs

### ISSUE THREAD

**Issue by yuxesd** [docsifyjs/docsify-cli#86]
$ docsify init ./docs

/usr/local/lib/node_modules/docsify-cli/node_modules/cp-file/index.js:60
		...options
		^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/docsify-cli/lib/commands/init.js:4:12)

**Comment by yuxesd** [comment]
系统：macOS High Sierra 10.13.6

**Comment by anikethsaha** [comment]
cc @jamesgeorge007 PTAL

**Comment by jamesgeorge007** [comment]
This seems to be a platform specific issue.
