### ISSUE TITLE
docsify:no such fille and directory

### ISSUE THREAD

**Issue by YeSei** [docsifyjs/docsify-cli#97]
Here is my install steps and solution attempts:
1: install docsify
`npm i docsify-cli -g`
exec:
`docsify -v`
`: no such file and directory`
I try intsall dos2unix:
`yum install dos2unix`
`dos2unix ../lib/node_modules/docsify-cli/bin/docsify`
and continue exec：
`docsify -v`
and I got：
```
/usr/lib/node_modules/docsify-cli/node_modules/cp-file/index.js:9
const cpFileAsync = async (source, destination, options, progressEmitter) => {
                          ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/docsify-cli/lib/commands/init.js:4:30)
```

There is my environment:
> Centos 7
> node v6.17.1
> docsify-cli@4.4.0

**Comment by YeSei** [comment]
when I update node version ,then Runing correctly.
